version: "3"
services:
  backend:
    container_name: backend
    build: .
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  beat:
    command: celery -A tasks beat --loglevel=info
    build:
      context: celery
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
  worker:
    command: celery -A tasks worker --loglevel=info
    build:
      context: celery
      dockerfile: Dockerfile
    environment:
      - CONTACTS_ENDPOINT=${CONTACTS_ENDPOINT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
  monitor:
    build:
      context: celery
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
    ports:
     - "6379:6379"